insert into Kata values (1,'Heian Shodan','Shotokan');
insert into Kata values (2,'Heian Nidan','Shotokan');
insert into Kata values (3,'Heian Sandan','Shotokan');
insert into Kata values (4,'Heian Yondan','Shotokan');
insert into Kata values (5,'Heian Godan','Shotokan');
insert into Kata values (6,'Gekisai Ichi','Goju Ryu');
insert into Kata values (7,'Gekisai Ni','Goju Ryu');
insert into Kata values (8,'Saifa','Goju Ryu');
insert into Kata values (9,'Seiyunchin','Goju Ryu');
insert into Kata values (10,'Sanseru','Goju Ryu');
insert into Kata values (11,'Pinan Shodan','Shito Ryu');
insert into Kata values (12,'Pinan Nidan','Shito Ryu');
insert into Kata values (13,'Pinan Sandan','Shito Ryu');
insert into Kata values (14,'Pinan Yondan','Shito Ryu');
insert into Kata values (15,'Pinan Godan','Shito Ryu');
insert into Kata values (16,'Pinan Shodan','Wado Ryu');
insert into Kata values (17,'Pinan Nidan','Wado Ryu');
insert into Kata values (18,'Pinan Sandan','Wado Ryu');
insert into Kata values (19,'Pinan Yondan','Wado Ryu');
insert into Kata values (20,'Pinan Godan','Wado Ryu');